---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name alertmanager-secret
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      templateFrom:
        - configMap:
            name: alertmanager-config-tpl
            items:
              - key: alertmanager.yaml
  dataFrom:
  - extract:
      key: alertmanager
  - extract:
      key: discord
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name thanos-objstore-secret
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        objstore.yml: |-
          config:
            access_key: {{ .AWS_ACCESS_KEY_ID }}
            bucket: thanos
            endpoint: 10.1.2.45:9000
            insecure: true
            region: ""
            secret_key: {{ .S3_SECRET_KEY }}
          type: s3
  dataFrom:
    - extract:
        key: thanos
