---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./authentik-charts.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./stakater.yaml
  - ./xenitab.yaml
  - ./external-secrets.yaml
  - ./dragonfly.yaml
  - ./crunchydata.yaml
