---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name postgres
spec:
  postgresVersion: 16
  patroni: # turn on sync writes to at least 1 other replica
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      replicas: &replica 2
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: postgres
                  postgres-operator.crunchydata.com/instance-set: postgres
  users:
    - name: "authentik"
      databases: ["authentik"]
      password:
        type: AlphaNumeric
    - name: "gatus"
      databases: ["gatus"]
      password:
        type: AlphaNumeric
    - name: "grafana"
      databases: ["grafana"]
      password:
        type: AlphaNumeric
    - name: "talos"
      databases: ["postgres", "authentik", "gatus", "grafana"]
      options: "CREATEDB CREATEROLE"
      password:
        type: AlphaNumeric
    - name: "talos1"
      databases: ["postgres", "authentik", "gatus", "grafana"]
      options: "CREATEDB CREATEROLE"
      password:
        type: AlphaNumeric
    - name: "postgres"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.49-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: openebs-hostpath
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  proxy:
    pgBouncer:
      service:
        metadata:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: cpgo.${SECRET_DOMAIN}
            io.cilium/lb-ipam-ips: 10.1.2.61
        type: LoadBalancer
      port: 5432
      replicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: postgres
                  postgres-operator.crunchydata.com/role: pgbouncer
