---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Authentik
        AUTHENTIK_BOOTSTRAP_EMAIL: '{{ .AUTHENTIK_EMAIL }}'
        AUTHENTIK_BOOTSTRAP_PASSWORD: '{{ .AUTHENTIK_PASSWORD }}'
        AUTHENTIK_BOOTSTRAP_TOKEN: '{{ .AUTHENTIK_TOKEN }}'
        AUTHENTIK_SECRET_KEY: '{{ .AUTHENTIK_SECRET_KEY }}'
        AUTHENTIK_REDIS__DB: "1"
  dataFrom:
  - extract:
      key: authentik
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: authentik-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        AUTHENTIK_POSTGRESQL__NAME: '{{ .dbname }}'
        AUTHENTIK_POSTGRESQL__HOST: '{{ index . "pgbouncer-host" }}'
        AUTHENTIK_POSTGRESQL__USER: '{{ .user }}'
        AUTHENTIK_POSTGRESQL__PASSWORD: '{{ .password }}'
        AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: 'true'
        AUTHENTIK_POSTGRESQL__SSLMODE: 'require'
  dataFrom:
  - extract:
      key: postgres-pguser-authentik
