apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:48VyaTLAKZ6YqHqZqmrFbIZA/RLW5diI57R1Msb6Ud6rYxsU5vwsgQ==,iv:FP7ff+n3VG1xTPzctwjIMoX1q9YQZ1bRm7jEAsTCNgg=,tag:yjjjgZmhN/C5PsNfs35jJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywymu9q0q2uc4me40qwrgqncky8vn48vwcfpvudwnt3j4vpcwcqs4uqgq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTklFRjJjSUpnelROSkE4
            NzRVZXpPZG9ONWRvTnE3U2FNbHpJUVlFRUQwCkk4ay8wa1krRkFoaXhaWTdDMEo1
            QlN2UytCMjMzdmpjMXhwZmxZZGVRN00KLS0tIDMxckMydktHUTFUb2F3ek1xUk41
            VHIvd0o0c2hGeDhxRXk2aUNHNGFScnMKOchIeCMc1uH6W6t/FFIDOziQNQo3tdj/
            GCfCNXufTJxjJt0mvJMo6OW+t9dFLGGs77bYbc+hrtsgmFoF9FwL+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T21:22:27Z"
    mac: ENC[AES256_GCM,data:bxri0QYGTu3zjxkXPdQX2bvlfWU6uhUV6tzJ2/3BlK72UJUVYd6mA5jLbW7ljCxPeKX6DdWP1DMgJuAAK2QW3cx+T3CT3hkBaAPKrNylWHYfhayUpoa9sd7pOAUcb+pOcc1EEeGQi8x3YX/PVB96Z+5SaeKSaI2M1vIR43WZWuI=,iv:DTV02q4/uhQFn4lGIQ1MLWW7TkOjbAWwPn/LxXGaCJo=,tag:7KsbmS+0zFxPp12K6BjR8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
