---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: nas
        group: infrastructure
        url: http://10.1.2.45/login
        interval: 1m
        conditions: ["[STATUS] == 200"]
        alerts: [{ type: discord }]
        ui:
          hide-url: true
          hide-hostname: true
