---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: discord.png
              href: 'https://discord.com/app'
        - Gmail:
            - icon: gmail.png
              href: 'http://gmail.com'
        - Google Calendar:
            - icon: google-calendar.png
              href: 'https://calendar.google.com'
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Spotify:
            - icon: spotify.png
              href: 'http://open.spotify.com'
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
        - k3s-home-cluster:
            - icon: github.png
              href: 'https://github.com/npmulder/talos-homelab'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Infrastructure:
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel Status
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
              key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
    - Storage:
        - TrueNas:
            href: https://truenas.local
            icon: unraid.png
            description: TrueNAS
  settings.yaml: |
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    background:
      image: https://raw.githubusercontent.com/smbonn2005/homeops/main/icons/moon.jpg
      opacity: 50
    color: slate
    headerStyle: clean
    layout:
      Calendar:
        style: column
        icon: mdi-calendar
      Media:
        style: column
        icon: mdi-play-circle
      Infrastructure:
        style: row
        columns: 3
        icon: mdi-server
      Storage:
        style: row
        columns: 2
        icon: mdi-desktop-tower
      Home:
        style: column
        icon: mdi-home-analytics
      Observability:
        style: column
        icon: mdi-chart-line
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
    # providers:
    #   longhorn:
    #     url: http://longhorn-frontend.storage
  widgets.yaml: |
    # - resources:
    #     backend: kubernetes
    #     cpu: true
    #     expanded: true
    #     memory: true
    - logo:
        icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/lds-transparent.png
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Howdy Hey!"
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
