---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/joryirving/home-assistant
              tag: 2024.5.3@sha256:49b00c8291298a23b08a9bc6bd7edf651e8e7e1ad43488c951b78e1413581302
            env:
              TZ: Europe/London
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 400Mi
              limits:
                memory: 700Mi
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.89.0
            env:
              TZ: Europe/London
            args:
              - "/config"
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        nameOverride: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "10.1.2.62"
        ports:
          http:
            port: 8123
      codeserver:
        controller: *app
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 8080
    ingress:
      app:
        className: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: Home-Assistant
          gethomepage.dev/icon: home-assistant.png
          gethomepage.dev/description: Home Automation Software
          gethomepage.dev/widget.type: homeassistant
          gethomepage.dev/widget.url: http://home-assistant.default:8123
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_HASS_TOKEN}}"
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host hass.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      codeserver:
        className: internal
        hosts:
          - host: &host hass-code.${SECRET_DOMAIN}
            paths:
            - path: /
              service:
                identifier: codeserver
                port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: *app
