apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:BYTBl+BHrnvBDdAu/33mudmJ2MaoTjUPQrZMMrKfhDxzRbI7oXi0/Q==,iv:B3P2KcodOmMvvPZtOXsLJ3IezSTf9WdX8iW559Hmq0E=,tag:CriCe4FNw5X1+EbDxmb9EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywymu9q0q2uc4me40qwrgqncky8vn48vwcfpvudwnt3j4vpcwcqs4uqgq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlKzBxWmo1Y0wyZ3pKT211
            QXQxSERzUkErRTE3UFFaSGtOWDNwb3JXVEFnCjY0UFlwU1NZT1MyNzZmeC9NbkVR
            amsxdmU0Um5VaWNscGp4cXlyQml0QlkKLS0tIFdZMmVZaHdjeFlFenV1aktXWlBM
            NGFDaG55Y2hQZDNmeWFiR2RFNFBmUEUKwioAyqG0ar6LCYXqzbg8FqR3RmdS+s18
            lU1TZ/yKFFowC0ylpg+SgeQr5FfghRBIKPeMDFRlPHaXJKKFwvWvNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T21:22:27Z"
    mac: ENC[AES256_GCM,data:63qxEiwaSGjh6kZpHjKAxebTzJPwpNxVM19UrlE37ZsVo6rX5Z4BZMVYlK+lUvqXDjH+/zRWm6wksfTairVkPKegpcivYkL55Z13T21aODskgXiFKJJhRNJ48ev5Vlj+s/7lMWi2fLr+8d8M8oXHLef7D0Gq2Z9lZg682fH/qhQ=,iv:fCB72TsYQH4W8RG95beSAuq8HEMTrMdJlWBrLA3iJDI=,tag:gP8fVdK2NK/SFKXGUTmyiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
